# Pure-data command catalog for kidney bot.
# Copyright (C) 2023  Alec Jensen
# Full license at LICENSE.md
#
# This module is the single source of truth for command documentation. It is
# consumed by:
#   - cogs/help.py            — the interactive /help Discord UI
#   - services/api's docs router — the public GET /api/docs/commands endpoint
#
# Zero discord.py / cog imports on purpose: this must stay importable from a
# plain Python process (e.g. the FastAPI service) with no Discord dependency.

from __future__ import annotations

from typing import Any

# ── Data helpers ──────────────────────────────────────────────────────────────

def _p(name: str, typ: str, required: bool, desc: str) -> dict[str, Any]:
    return {"name": name, "type": typ, "required": required, "desc": desc}


# ── Command catalogue ─────────────────────────────────────────────────────────
# Each command entry: name, usage, brief, description, params, perm, examples
# name     — full slash command as typed in Discord (with leading /)
# usage    — display string showing required/optional params
# brief    — one-liner shown in the category command list and select description
# description — multi-line detail shown in the command embed description
# params   — list of _p() dicts
# perm     — string, or None for no special permission required
# examples — list of example strings (without leading /)

CATEGORIES: dict[str, dict[str, Any]] = {
    "general": {
        "name": "General",
        "emoji": "💬",
        "description": "General information, bot setup, and utility commands.",
        "commands": [
            {
                "name": "/ping",
                "usage": "/ping",
                "brief": "Check the bot's response latency.",
                "description": "Returns the current WebSocket latency between the bot and Discord's gateway. Useful for confirming the bot is responsive.",
                "params": [],
                "perm": None,
                "examples": ["/ping"],
            },
            {
                "name": "/info",
                "usage": "/info",
                "brief": "View information about the bot.",
                "description": "Displays an overview of kidney bot including version, server count, links to the GitHub repository and support server, and credits.",
                "params": [],
                "perm": None,
                "examples": ["/info"],
            },
            {
                "name": "/invite",
                "usage": "/invite",
                "brief": "Get an invite link to add the bot to your server.",
                "description": "Sends the OAuth2 invite link with the required permissions pre-selected so you can add kidney bot to another server.",
                "params": [],
                "perm": None,
                "examples": ["/invite"],
            },
            {
                "name": "/devstats",
                "usage": "/devstats",
                "brief": "View bot system resource usage.",
                "description": "Shows CPU usage, memory consumption, and uptime metrics for the bot process. Primarily for the developer but available to everyone.",
                "params": [],
                "perm": None,
                "examples": ["/devstats"],
            },
            {
                "name": "/setup",
                "usage": "/setup",
                "brief": "Get set up with links to the web dashboard, or an in-Discord wizard.",
                "description": "Links you to the web dashboard's setup wizard and full settings page for your server. If no dashboard is configured, falls back to a guided in-Discord setup for Auto Role and Moderation. Run this right after adding the bot.",
                "params": [],
                "perm": None,
                "examples": ["/setup"],
            },
            {
                "name": "/guild_settings_overview",
                "usage": "/guild_settings_overview",
                "brief": "See all configured settings for this server.",
                "description": "Shows a complete snapshot of every setting currently configured for the server — autorole, automod, mod config, heuristics, honeypot, and network. Good for auditing the bot's state.",
                "params": [],
                "perm": "Administrator",
                "examples": ["/guild_settings_overview"],
            },
            {
                "name": "/set_announce_level",
                "usage": "/set_announce_level <level>",
                "brief": "Control what bot announcements you receive via DM.",
                "description": "Sets the level of announcements the bot will DM you when updates or notices are issued.\n\n**Levels:**\n• **None** — completely silent\n• **Critical** — outages and security notices only\n• **Update** — new feature announcements\n• **All** — everything, including minor changes",
                "params": [
                    _p("level", "choice", True, "None / Critical / Update / All — the minimum announcement level to receive."),
                ],
                "perm": None,
                "examples": ["/set_announce_level level:Critical", "/set_announce_level level:None"],
            },
        ],
    },

    "invites": {
        "name": "Invites",
        "emoji": "📨",
        "description": "Track who invited whom and log member joins with invite info.",
        "commands": [
            {
                "name": "/invites who",
                "usage": "/invites who <member>",
                "brief": "See who invited a member to this server.",
                "description": "Looks up the join record for a member and shows who invited them, which invite code they used, when they joined, and their heuristics score (if the engine was active when they joined).",
                "params": [_p("member", "member", True, "The member to look up.")],
                "perm": "Manage Guild",
                "examples": ["/invites who member:@Someone"],
            },
            {
                "name": "/invites invitees",
                "usage": "/invites invitees <member>",
                "brief": "List everyone a member has invited.",
                "description": "Shows every member in the join records who used an invite created by the given member. Each entry includes when they joined and their heuristics score. Sorted newest first.",
                "params": [_p("member", "member", True, "The member whose invitees to list.")],
                "perm": "Manage Guild",
                "examples": ["/invites invitees member:@Recruiter"],
            },
            {
                "name": "/invites tree",
                "usage": "/invites tree <member> [depth]",
                "brief": "Show the full invite chain from a member, recursively.",
                "description": "Builds an ASCII invite tree starting from the given member: everyone they invited, then everyone those people invited, and so on. `depth` controls how many levels to expand (1–5).\n\nEach node shows the member's join-time suspicion score and join time. Useful for tracing the root of a bot wave — find the invite source and see every account they brought in.\n\n✓ = a mod confirmed the flag was correct · ✗ FP = mod marked as false positive",
                "params": [
                    _p("member", "member", True, "The member to start the tree from."),
                    _p("depth", "number (1–5)", False, "How many levels deep to expand. Default: 3."),
                ],
                "perm": "Manage Guild",
                "examples": [
                    "/invites tree member:@Suspicious",
                    "/invites tree member:@Suspicious depth:5",
                ],
            },
            {
                "name": "/invites log",
                "usage": "/invites log [channel]",
                "brief": "Set or clear the invite log channel.",
                "description": "Configures a channel where every new member join is automatically logged as an embed showing: who joined, which invite code they used, who created that invite, and the new member's account age.\n\nLeave `channel` blank to disable the log.",
                "params": [
                    _p("channel", "channel", False, "The text channel to post join logs to. Leave blank to disable."),
                ],
                "perm": "Manage Guild",
                "examples": ["/invites log channel:#join-log", "/invites log"],
            },
        ],
    },

    "fun": {
        "name": "Fun",
        "emoji": "🎉",
        "description": "Games, jokes, images, and other entertainment.",
        "commands": [
            {
                "name": "/8ball",
                "usage": "/8ball <question>",
                "brief": "Ask the magic 8-ball a yes/no question.",
                "description": "The bot consults the mystical 8-ball and delivers a definitive answer to your most pressing questions. Completely authoritative; not to be questioned.",
                "params": [_p("question", "text", True, "The question you want answered.")],
                "perm": None,
                "examples": ["/8ball question:Will it rain today?"],
            },
            {
                "name": "/joke",
                "usage": "/joke",
                "brief": "Get a random joke.",
                "description": "Fetches a random joke from the joke database. Quality may vary.",
                "params": [],
                "perm": None,
                "examples": ["/joke"],
            },
            {
                "name": "/dadjoke",
                "usage": "/dadjoke",
                "brief": "Get a classic dad joke.",
                "description": "Returns a groan-worthy dad joke. You've been warned.",
                "params": [],
                "perm": None,
                "examples": ["/dadjoke"],
            },
            {
                "name": "/yomama",
                "usage": "/yomama",
                "brief": "Get a yo mama joke.",
                "description": "Delivers a yo mama joke. Handle with care.",
                "params": [],
                "perm": None,
                "examples": ["/yomama"],
            },
            {
                "name": "/shakespearean-insult",
                "usage": "/shakespearean-insult",
                "brief": "Insult someone in Early Modern English.",
                "description": "Generates a randomized Shakespearean insult. Perfect for when you want to be rude in a way that sounds educated.",
                "params": [],
                "perm": None,
                "examples": ["/shakespearean-insult"],
            },
            {
                "name": "/rps",
                "usage": "/rps",
                "brief": "Play rock-paper-scissors against the bot.",
                "description": "Challenges the bot to a game of rock-paper-scissors. Win beans if you beat the bot. Economy must be active.",
                "params": [],
                "perm": None,
                "examples": ["/rps"],
            },
            {
                "name": "/dog",
                "usage": "/dog",
                "brief": "Get a random dog photo.",
                "description": "Fetches a random dog photo from the internet. Guaranteed to be a good boy.",
                "params": [],
                "perm": None,
                "examples": ["/dog"],
            },
            {
                "name": "/cat",
                "usage": "/cat",
                "brief": "Get a random cat photo.",
                "description": "Fetches a random cat photo. May or may not care that you asked.",
                "params": [],
                "perm": None,
                "examples": ["/cat"],
            },
            {
                "name": "/duck",
                "usage": "/duck",
                "brief": "Get a random duck photo.",
                "description": "Fetches a random duck photo. Quack.",
                "params": [],
                "perm": None,
                "examples": ["/duck"],
            },
            {
                "name": "/meme",
                "usage": "/meme",
                "brief": "Get a random meme.",
                "description": "Fetches a random meme. Content varies wildly.",
                "params": [],
                "perm": None,
                "examples": ["/meme"],
            },
            {
                "name": "/wikipedia",
                "usage": "/wikipedia <query>",
                "brief": "Look up a Wikipedia article.",
                "description": "Searches Wikipedia for the given query and returns the first paragraph of the best-matching article. If it returns the wrong article, try a more specific query.",
                "params": [_p("query", "text", True, "Search terms to look up on Wikipedia.")],
                "perm": None,
                "examples": ["/wikipedia query:Python programming language"],
            },
            {
                "name": "/synonym",
                "usage": "/synonym <word>",
                "brief": "Get synonyms for a word.",
                "description": "Returns a list of synonyms for the provided word using a thesaurus lookup.",
                "params": [_p("word", "text", True, "The word to find synonyms for.")],
                "perm": None,
                "examples": ["/synonym word:happy"],
            },
            {
                "name": "/antonym",
                "usage": "/antonym <word>",
                "brief": "Get antonyms for a word.",
                "description": "Returns a list of antonyms (opposites) for the provided word.",
                "params": [_p("word", "text", True, "The word to find antonyms for.")],
                "perm": None,
                "examples": ["/antonym word:fast"],
            },
            {
                "name": "/fake-info",
                "usage": "/fake-info",
                "brief": "Generate a fake person's profile.",
                "description": "Generates a completely fabricated profile: fake name, address, phone number, email, and more. Powered by Faker. None of it is real.",
                "params": [],
                "perm": None,
                "examples": ["/fake-info"],
            },
            {
                "name": "/fight_under_this_flag",
                "usage": "/fight_under_this_flag [user] [flag] [flag_url]",
                "brief": "Generate an 'I will fight under this flag' meme.",
                "description": "Creates the classic meme image. Provide a user (uses their avatar), upload an image file, or provide a URL. At least one source must be given.",
                "params": [
                    _p("user", "member", False, "Use this member's avatar as the flag image."),
                    _p("flag", "attachment", False, "Upload an image file to use as the flag."),
                    _p("flag_url", "url", False, "URL of an image to use as the flag."),
                ],
                "perm": None,
                "examples": [
                    "/fight_under_this_flag user:@Someone",
                    "/fight_under_this_flag flag_url:https://example.com/image.png",
                ],
            },
            {
                "name": "/uwu_discord",
                "usage": "/uwu_discord [user] [flag] [flag_url]",
                "brief": "Generate a Discord uwu meme.",
                "description": "Creates the Discord uwu meme with a custom image. Same image sources as `/fight_under_this_flag` — use a member, upload a file, or provide a URL.",
                "params": [
                    _p("user", "member", False, "Use this member's avatar."),
                    _p("flag", "attachment", False, "Upload an image file."),
                    _p("flag_url", "url", False, "URL of an image."),
                ],
                "perm": None,
                "examples": ["/uwu_discord user:@Someone"],
            },
            {
                "name": "/rip",
                "usage": "/rip [user] [flag] [flag_url]",
                "brief": "Generate a RIP meme.",
                "description": "Creates a RIP meme with a custom image. Same image sources as the other meme commands.",
                "params": [
                    _p("user", "member", False, "Use this member's avatar."),
                    _p("flag", "attachment", False, "Upload an image file."),
                    _p("flag_url", "url", False, "URL of an image."),
                ],
                "perm": None,
                "examples": ["/rip user:@Someone"],
            },
        ],
    },

    "economy": {
        "name": "Economy",
        "emoji": "🫘",
        "description": "Earn, spend, and gamble beans — kidney bot's currency.",
        "commands": [
            {
                "name": "/balance",
                "usage": "/balance [user]",
                "brief": "Check your bean balance (or someone else's).",
                "description": "Shows the wallet and bank balance for yourself or another user. Wallet beans can be stolen with `/rob`; bank beans are safe. Transfer between them with `/deposit` and `/withdraw`.",
                "params": [_p("user", "user", False, "The user to check. Defaults to yourself.")],
                "perm": None,
                "examples": ["/balance", "/balance user:@Someone"],
            },
            {
                "name": "/beg",
                "usage": "/beg",
                "brief": "Beg for beans. 30-second cooldown.",
                "description": "Asks the universe for beans. You might get some, nothing, or a roast. There is a 30-second cooldown between uses.",
                "params": [],
                "perm": None,
                "examples": ["/beg"],
            },
            {
                "name": "/deposit",
                "usage": "/deposit <amount>",
                "brief": "Move beans from wallet to bank.",
                "description": "Transfers beans from your wallet into your bank account. Banked beans cannot be stolen by `/rob`. Amount can be a number, `all`, or `half`.",
                "params": [
                    _p("amount", "text", True, "How many beans to deposit. Use a number, `all`, or `half`."),
                ],
                "perm": None,
                "examples": ["/deposit amount:100", "/deposit amount:all"],
            },
            {
                "name": "/withdraw",
                "usage": "/withdraw <amount>",
                "brief": "Move beans from bank to wallet.",
                "description": "Withdraws beans from your bank back into your wallet. Amount can be a number, `all`, or `half`.",
                "params": [
                    _p("amount", "text", True, "How many beans to withdraw. Use a number, `all`, or `half`."),
                ],
                "perm": None,
                "examples": ["/withdraw amount:500", "/withdraw amount:half"],
            },
            {
                "name": "/rob",
                "usage": "/rob <target>",
                "brief": "Steal beans from another user's wallet. 30-second cooldown.",
                "description": "Attempts to steal beans from another user's wallet. The amount stolen depends on how many they have. Robbing can fail and you may lose beans if you get caught. Bank beans cannot be robbed.",
                "params": [_p("target", "user", True, "The user you want to rob.")],
                "perm": None,
                "examples": ["/rob target:@RichGuy"],
            },
            {
                "name": "/pay",
                "usage": "/pay <target> <amount>",
                "brief": "Send beans to another user.",
                "description": "Transfers beans from your wallet to another user's wallet. Both users must have an account.",
                "params": [
                    _p("target", "user", True, "The user to send beans to."),
                    _p("amount", "number", True, "How many beans to send."),
                ],
                "perm": None,
                "examples": ["/pay target:@Friend amount:250"],
            },
            {
                "name": "/shop",
                "usage": "/shop",
                "brief": "Browse available items in the shop.",
                "description": "Displays all purchasable items, their prices, and descriptions. Use `/buy` to purchase something.",
                "params": [],
                "perm": None,
                "examples": ["/shop"],
            },
            {
                "name": "/buy",
                "usage": "/buy <item>",
                "brief": "Purchase an item from the shop.",
                "description": "Buys an item from the shop and adds it to your inventory. Use `/shop` to see available items.",
                "params": [_p("item", "choice", True, "The item to purchase. Supports autocomplete.")],
                "perm": None,
                "examples": ["/buy item:shield"],
            },
            {
                "name": "/use",
                "usage": "/use <item>",
                "brief": "Use an item from your inventory.",
                "description": "Activates an item from your inventory. Different items have different effects. Autocomplete will only suggest items you currently own.",
                "params": [_p("item", "text", True, "The item to use. Supports autocomplete.")],
                "perm": None,
                "examples": ["/use item:shield"],
            },
            {
                "name": "/inventory",
                "usage": "/inventory",
                "brief": "View your item inventory.",
                "description": "Lists all items currently in your inventory with quantities and descriptions.",
                "params": [],
                "perm": None,
                "examples": ["/inventory"],
            },
        ],
    },

    "music": {
        "name": "Music",
        "emoji": "🎵",
        "description": "Play music in voice channels from YouTube and Spotify.",
        "commands": [
            {
                "name": "/play",
                "usage": "/play <query>",
                "brief": "Play a song or add it to the queue.",
                "description": "Plays audio in your current voice channel. Supports:\n• YouTube video URLs\n• YouTube search terms\n• Spotify track, album, or playlist URLs\n\nIf something is already playing the track is added to the queue. The bot joins your voice channel automatically.",
                "params": [_p("query", "text", True, "YouTube URL, Spotify URL, or search terms.")],
                "perm": None,
                "examples": [
                    "/play query:Never Gonna Give You Up",
                    "/play query:https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                    "/play query:https://open.spotify.com/track/...",
                ],
            },
            {
                "name": "/pause",
                "usage": "/pause",
                "brief": "Pause the current track.",
                "description": "Pauses playback. Use `/resume` to continue from the same position.",
                "params": [],
                "perm": None,
                "examples": ["/pause"],
            },
            {
                "name": "/resume",
                "usage": "/resume",
                "brief": "Resume paused playback.",
                "description": "Resumes playback if paused.",
                "params": [],
                "perm": None,
                "examples": ["/resume"],
            },
            {
                "name": "/stop",
                "usage": "/stop",
                "brief": "Stop playback and clear the queue.",
                "description": "Stops the current track and empties the entire queue. The bot remains in the voice channel.",
                "params": [],
                "perm": None,
                "examples": ["/stop"],
            },
            {
                "name": "/skip",
                "usage": "/skip",
                "brief": "Skip to the next song in the queue.",
                "description": "Skips the currently playing track and immediately starts the next one. If the queue is empty, playback stops.",
                "params": [],
                "perm": None,
                "examples": ["/skip"],
            },
            {
                "name": "/leave",
                "usage": "/leave",
                "brief": "Disconnect the bot from the voice channel.",
                "description": "Disconnects the bot from the voice channel and stops playback.",
                "params": [],
                "perm": None,
                "examples": ["/leave"],
            },
            {
                "name": "/queue",
                "usage": "/queue",
                "brief": "Show the current playback queue.",
                "description": "Displays the queue of upcoming tracks including the currently playing song and the total count.",
                "params": [],
                "perm": None,
                "examples": ["/queue"],
            },
            {
                "name": "/nowplaying",
                "usage": "/nowplaying",
                "brief": "Show what's currently playing.",
                "description": "Displays the currently playing track with its title, source, duration, and a progress indicator.",
                "params": [],
                "perm": None,
                "examples": ["/nowplaying"],
            },
            {
                "name": "/remove",
                "usage": "/remove <position>",
                "brief": "Remove a track from the queue by position.",
                "description": "Removes the track at the given position from the queue. Use `/queue` to see position numbers (positions are 1-based).",
                "params": [_p("position", "number", True, "The 1-based position of the track to remove.")],
                "perm": None,
                "examples": ["/remove position:3"],
            },
            {
                "name": "/clear",
                "usage": "/clear",
                "brief": "Clear all tracks from the queue.",
                "description": "Empties the entire upcoming queue without stopping the currently playing song.",
                "params": [],
                "perm": None,
                "examples": ["/clear"],
            },
            {
                "name": "/shuffle",
                "usage": "/shuffle",
                "brief": "Randomly shuffle the queue.",
                "description": "Randomly reorders all tracks in the queue. Does not affect the currently playing song.",
                "params": [],
                "perm": None,
                "examples": ["/shuffle"],
            },
            {
                "name": "/loop",
                "usage": "/loop",
                "brief": "Cycle through loop modes (Off → Track → Queue).",
                "description": "Cycles the loop mode:\n• **Off** — no looping, queue plays through once.\n• **Track** — current song repeats indefinitely.\n• **Queue** — the entire queue loops when it ends.",
                "params": [],
                "perm": None,
                "examples": ["/loop"],
            },
            {
                "name": "/volume",
                "usage": "/volume <level>",
                "brief": "Set playback volume (0–100).",
                "description": "Adjusts the playback volume. Range is 0 (muted) to 100 (maximum). Changes take effect immediately.",
                "params": [
                    _p("level", "number (0–100)", True, "Volume level from 0 (muted) to 100 (max)."),
                ],
                "perm": None,
                "examples": ["/volume level:75", "/volume level:0"],
            },
            {
                "name": "/seek",
                "usage": "/seek <position>",
                "brief": "Jump to a position in the current track.",
                "description": "Seeks to the given timestamp in the currently playing track.\n\n**Accepted formats:** `mm:ss`, `hh:mm:ss`, or raw seconds.",
                "params": [
                    _p("position", "text", True, "Timestamp to seek to. Formats: `mm:ss`, `hh:mm:ss`, or seconds."),
                ],
                "perm": None,
                "examples": ["/seek position:1:30", "/seek position:90"],
            },
        ],
    },

    "moderation": {
        "name": "Moderation",
        "emoji": "🛡️",
        "description": "Manage members, record actions, and view moderation history.",
        "commands": [
            {
                "name": "/warn",
                "usage": "/warn <user> <reason>",
                "brief": "Issue a formal warning to a member.",
                "description": "Records a warning in the member's moderation history and notifies them via DM. Warnings accumulate and can trigger escalation suggestions (see `/modconfig`).",
                "params": [
                    _p("user", "member", True, "The member to warn."),
                    _p("reason", "text", True, "The reason for the warning. Stored in mod history."),
                ],
                "perm": "Manage Messages",
                "examples": ["/warn user:@Someone reason:Spamming in #general"],
            },
            {
                "name": "/mute",
                "usage": "/mute <user> [reason]",
                "brief": "Apply a role-based mute to a member.",
                "description": "Assigns the configured Muted role to a member, preventing them from sending messages. This is permanent until undone with `/unmute`. Requires a Muted role to be configured.",
                "params": [
                    _p("user", "member", True, "The member to mute."),
                    _p("reason", "text", False, "The reason for the mute."),
                ],
                "perm": "Mute Members",
                "examples": ["/mute user:@Loudmouth reason:Repeated noise violations"],
            },
            {
                "name": "/unmute",
                "usage": "/unmute <user>",
                "brief": "Remove a role-based mute from a member.",
                "description": "Removes the Muted role from a member, restoring their ability to send messages.",
                "params": [_p("user", "member", True, "The member to unmute.")],
                "perm": "Mute Members",
                "examples": ["/unmute user:@Loudmouth"],
            },
            {
                "name": "/tempmute",
                "usage": "/tempmute <user> <time> [reason]",
                "brief": "Apply a Discord-native timeout for a set duration.",
                "description": "Applies a Discord timeout to a member for a set duration. While timed out the member cannot send messages, react, or join voice channels. The timeout expires automatically.\n\n**Time formats:** `10m`, `2h`, `1d`, `1w` (max 28 days).",
                "params": [
                    _p("user", "member", True, "The member to timeout."),
                    _p("time", "text", True, "Duration of the timeout. E.g. `10m`, `2h`, `1d`, `1w`."),
                    _p("reason", "text", False, "The reason for the timeout."),
                ],
                "perm": "Mute Members",
                "examples": [
                    "/tempmute user:@Spammer time:1h reason:Flooding chat",
                    "/tempmute user:@Someone time:1d",
                ],
            },
            {
                "name": "/kick",
                "usage": "/kick <users> [reason] [delete_message_time]",
                "brief": "Kick one or more members.",
                "description": "Kicks one or more members from the server. Kicked members can rejoin via invite.\n\n**users** accepts comma-separated user IDs or mentions, enabling bulk kicks in one command.\n\n**delete_message_time** deletes recent messages from those users (e.g. `7d`, `24h`, `30m`).",
                "params": [
                    _p("users", "text", True, "Comma-separated member mentions or IDs. E.g. `@User1, @User2, 123456789`."),
                    _p("reason", "text", False, "Reason for the kick."),
                    _p("delete_message_time", "text", False, "Delete their messages within this window. Format: `7d`, `24h`, `30m`."),
                ],
                "perm": "Kick Members",
                "examples": [
                    "/kick users:@Rulebreaker reason:Hate speech",
                    "/kick users:123456,789012 reason:Raiding delete_message_time:1h",
                ],
            },
            {
                "name": "/ban",
                "usage": "/ban <users> [reason] [delete_message_time]",
                "brief": "Ban one or more users permanently.",
                "description": "Permanently bans one or more users from the server. Accepts comma-separated user IDs or mentions for bulk banning — you can ban users who have already left.\n\n**delete_message_time** deletes their recent messages (max 7 days).",
                "params": [
                    _p("users", "text", True, "Comma-separated user mentions or IDs. Can ban users not currently in the server."),
                    _p("reason", "text", False, "Reason for the ban, shown in audit log and stored in mod history."),
                    _p("delete_message_time", "text", False, "Delete their messages within this window. Max 7 days. Format: `7d`, `24h`."),
                ],
                "perm": "Ban Members",
                "examples": [
                    "/ban users:@Raider reason:Raiding delete_message_time:7d",
                    "/ban users:123456789 reason:Evading previous ban",
                ],
            },
            {
                "name": "/unban",
                "usage": "/unban <users> [reason]",
                "brief": "Unban one or more users.",
                "description": "Lifts the ban on one or more users. Accepts comma-separated user IDs.",
                "params": [
                    _p("users", "text", True, "Comma-separated user IDs to unban."),
                    _p("reason", "text", False, "Reason for the unban."),
                ],
                "perm": "Ban Members",
                "examples": ["/unban users:123456789 reason:Ban appeal approved"],
            },
            {
                "name": "/purge",
                "usage": "/purge <limit> [user]",
                "brief": "Bulk-delete messages from a channel.",
                "description": "Deletes up to the specified number of recent messages in the current channel. If a user is specified, only that user's messages are deleted (the bot still scans the full `limit` of messages to find them).\n\nDiscord limits bulk deletion to messages less than 14 days old.",
                "params": [
                    _p("limit", "number", True, "How many messages to scan and delete. Max: 100."),
                    _p("user", "member", False, "Only delete messages from this specific member."),
                ],
                "perm": "Manage Messages",
                "examples": ["/purge limit:50", "/purge limit:100 user:@Spammer"],
            },
            {
                "name": "/nickname",
                "usage": "/nickname <user> [newnick]",
                "brief": "Change or reset a member's nickname.",
                "description": "Sets a new nickname for a member. Leave `newnick` blank to reset their nickname back to their username.",
                "params": [
                    _p("user", "member", True, "The member whose nickname to change."),
                    _p("newnick", "text", False, "The new nickname. Leave blank to reset to username."),
                ],
                "perm": "Manage Nicknames",
                "examples": ["/nickname user:@Someone newnick:Cool Dude", "/nickname user:@Someone"],
            },
            {
                "name": "/history",
                "usage": "/history <user>",
                "brief": "View a member's moderation history.",
                "description": "Displays a paginated list of all moderation actions taken against a member in this server: warnings, mutes, kicks, bans, and unbans. Includes the moderator, reason, and timestamp for each entry.",
                "params": [_p("user", "member", True, "The member to look up.")],
                "perm": "Manage Messages",
                "examples": ["/history user:@Someone"],
            },
            {
                "name": "/actioninfo",
                "usage": "/actioninfo <action_id>",
                "brief": "Look up a specific moderation action by ID.",
                "description": "Retrieves full details about a single moderation action using its unique ID. Action IDs are shown in the moderation history and in log channel embeds.",
                "params": [
                    _p("action_id", "text", True, "The unique action ID shown in `/history` entries or the mod log channel."),
                ],
                "perm": "Manage Messages",
                "examples": ["/actioninfo action_id:abc123def456"],
            },
            {
                "name": "/clearhistory",
                "usage": "/clearhistory <user>",
                "brief": "Wipe all moderation history for a member.",
                "description": "Permanently deletes every moderation action on record for a member in this server. This cannot be undone.",
                "params": [_p("user", "member", True, "The member whose history to erase.")],
                "perm": "Administrator",
                "examples": ["/clearhistory user:@Someone"],
            },
            {
                "name": "/removeaction",
                "usage": "/removeaction <action_id>",
                "brief": "Remove a single action from a member's history.",
                "description": "Deletes one specific action from the moderation log by its ID. Use this to correct mistakes without wiping the entire history.",
                "params": [_p("action_id", "text", True, "The unique action ID to remove.")],
                "perm": "Manage Messages",
                "examples": ["/removeaction action_id:abc123def456"],
            },
        ],
    },

    "setup": {
        "name": "Server Setup",
        "emoji": "⚙️",
        "description": "Configure autorole, automod, moderation settings, and message behavior.",
        "commands": [
            {
                "name": "/autorole add",
                "usage": "/autorole add <role> [delay]",
                "brief": "Add a role to the autorole list.",
                "description": "Adds a role to the list of roles automatically given to members when they join. If `delay` is set, the role is assigned after that many seconds — useful for verification cooldowns.",
                "params": [
                    _p("role", "role", True, "The role to automatically assign to new members."),
                    _p("delay", "number", False, "Seconds to wait before assigning. Defaults to 0 (immediate)."),
                ],
                "perm": "Manage Guild",
                "examples": ["/autorole add role:@Member", "/autorole add role:@Verified delay:300"],
            },
            {
                "name": "/autorole remove",
                "usage": "/autorole remove <role>",
                "brief": "Remove a role from the autorole list.",
                "description": "Stops a role from being automatically assigned to new members.",
                "params": [_p("role", "role", True, "The role to remove from the autorole list.")],
                "perm": "Manage Guild",
                "examples": ["/autorole remove role:@Member"],
            },
            {
                "name": "/autorole delay",
                "usage": "/autorole delay <role> <delay>",
                "brief": "Update the delay for an existing autorole.",
                "description": "Changes how many seconds to wait before assigning a role already in the autorole list.",
                "params": [
                    _p("role", "role", True, "The role to update."),
                    _p("delay", "number", True, "New delay in seconds."),
                ],
                "perm": "Manage Guild",
                "examples": ["/autorole delay role:@Member delay:60"],
            },
            {
                "name": "/autorole list",
                "usage": "/autorole list",
                "brief": "List all configured autoroles and their delays.",
                "description": "Shows every role in the autorole list along with each role's configured delay.",
                "params": [],
                "perm": "Manage Guild",
                "examples": ["/autorole list"],
            },
            {
                "name": "/autorole settings",
                "usage": "/autorole settings <option> <value>",
                "brief": "Adjust miscellaneous autorole behavior.",
                "description": "Configures extra autorole options.\n\n**bots_get_roles** — Whether bots added to the server also receive autoroles. Defaults to off since bots usually shouldn't get member roles.",
                "params": [
                    _p("option", "choice", True, "The setting to change. Currently: `bots_get_roles`."),
                    _p("value", "bool", True, "True or False."),
                ],
                "perm": "Manage Guild",
                "examples": ["/autorole settings option:bots_get_roles value:False"],
            },
            {
                "name": "/automod log",
                "usage": "/automod log <channel>",
                "brief": "Set the channel for automod log messages.",
                "description": "Configures the channel where automod action notifications are posted when a user is automatically warned, muted, or flagged.",
                "params": [_p("channel", "channel", True, "The text channel to post automod logs to.")],
                "perm": "Manage Guild",
                "examples": ["/automod log channel:#mod-log"],
            },
            {
                "name": "/automod whitelist",
                "usage": "/automod whitelist [state] [user] [channel]",
                "brief": "Whitelist a user or channel from automod.",
                "description": "Adds a user or channel to the automod whitelist so they are not affected by automod rules. Provide either `user` or `channel` — not both. Use `state:False` to remove from the whitelist.",
                "params": [
                    _p("state", "bool", False, "True to add to whitelist (default), False to remove."),
                    _p("user", "user", False, "The user to whitelist."),
                    _p("channel", "channel", False, "The channel to whitelist."),
                ],
                "perm": "Manage Guild",
                "examples": ["/automod whitelist user:@Trusted", "/automod whitelist channel:#bot-spam"],
            },
            {
                "name": "/modconfig log_channel",
                "usage": "/modconfig log_channel [channel]",
                "brief": "Set or clear the moderation log channel.",
                "description": "Sets the channel where moderation actions (warns, kicks, bans, etc.) are logged as embeds. Leave `channel` blank to disable logging.",
                "params": [_p("channel", "channel", False, "The text channel for mod logs. Leave blank to disable.")],
                "perm": "Administrator",
                "examples": ["/modconfig log_channel channel:#mod-log", "/modconfig log_channel"],
            },
            {
                "name": "/modconfig require_reason",
                "usage": "/modconfig require_reason <require>",
                "brief": "Require a reason for moderation actions.",
                "description": "When enabled, warns, mutes, timeouts, kicks, and bans must include a reason or the command is rejected.",
                "params": [_p("require", "choice", True, "Yes to require a reason, No to make it optional.")],
                "perm": "Manage Guild",
                "examples": ["/modconfig require_reason require:Yes"],
            },
            {
                "name": "/modconfig escalation_view",
                "usage": "/modconfig escalation_view",
                "brief": "View the current automatic escalation rules.",
                "description": "Shows escalation rules that determine what actions the bot suggests when a member accumulates multiple violations. Example: 3 warns in 7 days → suggest timeout.",
                "params": [],
                "perm": "Administrator",
                "examples": ["/modconfig escalation_view"],
            },
            {
                "name": "/modconfig escalation_reset",
                "usage": "/modconfig escalation_reset",
                "brief": "Reset escalation rules to defaults.",
                "description": "Clears all custom escalation rules and restores built-in defaults: 3 warns → timeout, 5 warns → kick, 2 kicks → ban.",
                "params": [],
                "perm": "Administrator",
                "examples": ["/modconfig escalation_reset"],
            },
            {
                "name": "/ephemeral_messages guild",
                "usage": "/ephemeral_messages guild <ephemeral>",
                "brief": "Control whether mod responses are public or private server-wide.",
                "description": "Sets whether moderation command responses are ephemeral (visible only to the mod) or public. `Yes` = private, `No` = everyone in the channel sees it.",
                "params": [
                    _p("ephemeral", "choice", True, "Yes to make mod responses ephemeral, No for public."),
                ],
                "perm": "Administrator",
                "examples": ["/ephemeral_messages guild ephemeral:Yes"],
            },
            {
                "name": "/ephemeral_messages self",
                "usage": "/ephemeral_messages self <ephemeral>",
                "brief": "Set your personal ephemeral preference for mod commands.",
                "description": "Overrides the guild setting for your own moderation commands only. Useful if you want different behavior from the server default.",
                "params": [_p("ephemeral", "choice", True, "Yes for ephemeral, No for public.")],
                "perm": "Administrator",
                "examples": ["/ephemeral_messages self ephemeral:No"],
            },
            {
                "name": "/ephemeral_messages force_guild_setting",
                "usage": "/ephemeral_messages force_guild_setting <force>",
                "brief": "Force the guild ephemeral setting over per-user preferences.",
                "description": "When enabled, the guild-level ephemeral setting overrides any individual moderator's personal preference.",
                "params": [
                    _p("force", "choice", True, "Yes to enforce guild setting, No to allow personal overrides."),
                ],
                "perm": "Administrator",
                "examples": ["/ephemeral_messages force_guild_setting force:Yes"],
            },
        ],
    },

    "antiraid": {
        "name": "Anti-Raid",
        "emoji": "🔍",
        "description": "Heuristics engine and honeypot channel to detect and stop bot raids.",
        "commands": [
            {
                "name": "/scan",
                "usage": "/scan <member>",
                "brief": "Run a heuristics scan on a member on demand.",
                "description": "Manually evaluates a member through the heuristics engine and returns their suspicion score along with every signal that fired. Useful for checking a specific member without waiting for a join event.",
                "params": [_p("member", "member", True, "The member to scan.")],
                "perm": "Kick Members",
                "examples": ["/scan member:@SuspiciousUser"],
            },
            {
                "name": "/heuristics enable",
                "usage": "/heuristics enable <enabled>",
                "brief": "Turn the heuristics engine on or off.",
                "description": "Enables or disables the heuristics engine for this server. When disabled, no joins are scored and no automatic actions are taken.",
                "params": [_p("enabled", "bool", True, "True to enable, False to disable.")],
                "perm": "Manage Guild",
                "examples": ["/heuristics enable enabled:True"],
            },
            {
                "name": "/heuristics alert_channel",
                "usage": "/heuristics alert_channel <channel>",
                "brief": "Set the channel for suspicious join alerts.",
                "description": "Configures the channel where the bot posts an alert embed whenever a new join scores above the alert threshold. Each alert includes the member's score and every signal that fired.",
                "params": [_p("channel", "channel", True, "The text channel to post alerts to.")],
                "perm": "Manage Guild",
                "examples": ["/heuristics alert_channel channel:#raid-alerts"],
            },
            {
                "name": "/heuristics review_channel",
                "usage": "/heuristics review_channel <channel>",
                "brief": "Set the channel for the mod review queue.",
                "description": "Configures the channel where the bot posts borderline joins — members who scored above the alert threshold but triggered no automatic action. Each post has **Approve / Kick / Ban** buttons so mods can act directly. Ban opens a follow-up prompt to choose how much message history to delete before confirming. These buttons survive bot restarts.",
                "params": [_p("channel", "channel", True, "The text channel for the review queue.")],
                "perm": "Manage Guild",
                "examples": ["/heuristics review_channel channel:#review-queue"],
            },
            {
                "name": "/heuristics auto_delete",
                "usage": "/heuristics auto_delete <enabled> [window_hours] [score_threshold]",
                "brief": "Auto-delete message history on heuristics auto-bans.",
                "description": "Configures whether the bot deletes a banned member's recent message history automatically when the heuristics engine auto-bans them (score ≥ ban threshold). **Disabled by default.**\n\nWhen enabled, deletes the last `window_hours` of messages (default 24h, max 168h/7 days — Discord's limit). Optionally set `score_threshold` to only auto-delete for especially high-confidence bans; omit it to apply to every auto-ban.\n\nThis only affects automatic bans from the engine — manual bans via the review queue or moderation insight panel always let you choose the delete window yourself.",
                "params": [
                    _p("enabled", "bool", True, "True to enable auto-delete on auto-ban, False to disable."),
                    _p("window_hours", "number (1–168)", False, "Hours of message history to delete. Default: 24."),
                    _p("score_threshold", "number", False, "Only auto-delete if score is at least this high. Default: applies to all auto-bans."),
                ],
                "perm": "Manage Guild",
                "examples": [
                    "/heuristics auto_delete enabled:True",
                    "/heuristics auto_delete enabled:True window_hours:6 score_threshold:90",
                    "/heuristics auto_delete enabled:False",
                ],
            },
            {
                "name": "/heuristics thresholds",
                "usage": "/heuristics thresholds [alert] [mute] [kick] [ban]",
                "brief": "View or set automated action thresholds.",
                "description": "Sets the suspicion score (0–100) at which each action fires. Omit any parameter to leave it unchanged.\n\n• **alert** — Post an alert (default: 35). Always active.\n• **mute** — Apply a 24-hour timeout. Default: 101 (disabled).\n• **kick** — Kick the member. Default: 101 (disabled).\n• **ban** — Immediate ban. Default: 101 (disabled).\n\nAuto-mute, kick, and ban are **disabled by default** (threshold 101, which no score can reach). Lower a threshold to enable it — e.g. `kick:70 ban:90`.",
                "params": [
                    _p("alert", "number", False, "Alert threshold (0–100). Default: 40."),
                    _p("mute", "number", False, "Auto-mute threshold. Default: 101 (disabled)."),
                    _p("kick", "number", False, "Auto-kick threshold. Default: 101 (disabled)."),
                    _p("ban", "number", False, "Auto-ban threshold. Default: 101 (disabled)."),
                ],
                "perm": "Manage Guild",
                "examples": [
                    "/heuristics thresholds alert:30 kick:70 ban:90",
                    "/heuristics thresholds",
                ],
            },
            {
                "name": "/heuristics thresholds_reset",
                "usage": "/heuristics thresholds_reset",
                "brief": "Reset all action thresholds to defaults.",
                "description": "Clears all threshold overrides and restores defaults (alert: 35; mute/kick/ban: 101 — all automatic punishments disabled).",
                "params": [],
                "perm": "Manage Guild",
                "examples": ["/heuristics thresholds_reset"],
            },
            {
                "name": "/heuristics tracking_days",
                "usage": "/heuristics tracking_days <days>",
                "brief": "Set how long new members are monitored after joining.",
                "description": "After a flagged join, the bot monitors the member's behavior (spam, link posting, mention spam, etc.) for this many days. Must be 1–30. Default: 7 days.\n\nAt the end of the tracking window, well-behaved members are marked as trusted in the network reputation system.",
                "params": [_p("days", "number (1–30)", True, "Number of days to track post-join behavior.")],
                "perm": "Manage Guild",
                "examples": ["/heuristics tracking_days days:14"],
            },
            {
                "name": "/heuristics weights_export",
                "usage": "/heuristics weights_export",
                "brief": "Download current signal weights as a JSON file.",
                "description": "Exports all signal weights (how much each signal adds to a member's suspicion score) as a JSON file. Useful for reviewing your configuration or backing it up before making changes with `/heuristics weights_import`.",
                "params": [],
                "perm": "Manage Guild",
                "examples": ["/heuristics weights_export"],
            },
            {
                "name": "/heuristics weights_import",
                "usage": "/heuristics weights_import <file>",
                "brief": "Upload a JSON file to override signal weights.",
                "description": "Imports signal weight overrides from a JSON file. Only keys that match valid signal names are accepted; unknown keys are rejected. Use `/heuristics weights_export` first to get the correct format.",
                "params": [
                    _p("file", "attachment (.json)", True, "A .json file exported from `/heuristics weights_export`."),
                ],
                "perm": "Manage Guild",
                "examples": ["/heuristics weights_import file:weights.json"],
            },
            {
                "name": "/heuristics weights_reset",
                "usage": "/heuristics weights_reset",
                "brief": "Remove all weight overrides and restore defaults.",
                "description": "Deletes all per-server signal weight overrides so the engine returns to its default tuning.",
                "params": [],
                "perm": "Manage Guild",
                "examples": ["/heuristics weights_reset"],
            },
            {
                "name": "/heuristics stats",
                "usage": "/heuristics stats",
                "brief": "Show detection statistics for the last 30 days.",
                "description": "Displays a breakdown of the heuristics engine's activity: total flagged joins, automatic actions taken by type, how many flags were later confirmed by mods vs. false positives, and a computed precision metric.",
                "params": [],
                "perm": "Manage Guild",
                "examples": ["/heuristics stats"],
            },
            {
                "name": "/heuristics status",
                "usage": "/heuristics status",
                "brief": "Show the current heuristics configuration.",
                "description": "Displays a summary of all heuristics settings for this server: whether the engine is enabled, alert and review channels, tracking window, all action thresholds, and whether any signal weight overrides are active.",
                "params": [],
                "perm": "Manage Guild",
                "examples": ["/heuristics status"],
            },
            {
                "name": "/honeypot enable",
                "usage": "/honeypot enable <channel> [mode] [action]",
                "brief": "Enable the honeypot verification channel.",
                "description": "Sets up a honeypot channel that appears accessible to new members. A verification embed with a button is posted. Any member who **sends a message** (instead of clicking Verify) is treated as a bot.\n\n**Modes:**\n• **visibility** — Channel is hidden from verified members via role (default).\n• **lockdown** — Members get a pending role on join that restricts all channels except the honeypot.\n\n**Actions:** kick (default), ban, or mute (24h timeout).",
                "params": [
                    _p("channel", "channel", True, "The channel to use as the honeypot."),
                    _p("mode", "choice", False, "`visibility` (default) or `lockdown`."),
                    _p("action", "choice", False, "What to do when someone messages: `kick` (default), `ban`, or `mute`."),
                ],
                "perm": "Manage Guild",
                "examples": [
                    "/honeypot enable channel:#verify",
                    "/honeypot enable channel:#verify mode:lockdown action:ban",
                ],
            },
            {
                "name": "/honeypot disable",
                "usage": "/honeypot disable",
                "brief": "Disable the honeypot.",
                "description": "Turns off the honeypot. The verification message stays in the channel but new messages will not trigger any action.",
                "params": [],
                "perm": "Manage Guild",
                "examples": ["/honeypot disable"],
            },
            {
                "name": "/honeypot action",
                "usage": "/honeypot action <action>",
                "brief": "Change the action taken when someone messages the honeypot.",
                "description": "Updates the action taken when a member sends a message in the honeypot channel. Does not change the channel or mode.",
                "params": [_p("action", "choice", True, "`kick`, `ban`, or `mute` (24h timeout).")],
                "perm": "Manage Guild",
                "examples": ["/honeypot action action:ban"],
            },
            {
                "name": "/honeypot alert_channel",
                "usage": "/honeypot alert_channel <channel>",
                "brief": "Set the channel for honeypot trigger alerts.",
                "description": "Configures where the bot posts an alert when a member triggers the honeypot, including the message content they sent and the action taken.",
                "params": [_p("channel", "channel", True, "The text channel for honeypot alerts.")],
                "perm": "Manage Guild",
                "examples": ["/honeypot alert_channel channel:#mod-alerts"],
            },
            {
                "name": "/honeypot verify_role",
                "usage": "/honeypot verify_role <role>",
                "brief": "Set the role added when a member verifies (visibility mode).",
                "description": "In **visibility mode**, this role is added to a member when they click Verify. Configure a DENY permission overwrite on this role for the honeypot channel so verified members can no longer see it.",
                "params": [_p("role", "role", True, "The role to add when a member verifies.")],
                "perm": "Manage Guild",
                "examples": ["/honeypot verify_role role:@Verified"],
            },
            {
                "name": "/honeypot pending_role",
                "usage": "/honeypot pending_role <role>",
                "brief": "Set the role given on join (lockdown mode).",
                "description": "In **lockdown mode**, this role is assigned to every new member when they join. Configure this role to DENY access to all channels except the honeypot. The role is removed when the member clicks Verify.",
                "params": [_p("role", "role", True, "The role assigned on join to restrict channel access.")],
                "perm": "Manage Guild",
                "examples": ["/honeypot pending_role role:@Unverified"],
            },
            {
                "name": "/honeypot status",
                "usage": "/honeypot status",
                "brief": "Show the current honeypot configuration.",
                "description": "Displays all honeypot settings: whether it's enabled, the channel, mode, action, alert channel, and any configured roles.",
                "params": [],
                "perm": "Manage Guild",
                "examples": ["/honeypot status"],
            },
        ],
    },

    "network": {
        "name": "Network",
        "emoji": "🌐",
        "description": "Connect multiple servers for shared bans, raid alerts, and reputation.",
        "commands": [
            {
                "name": "/network create",
                "usage": "/network create <name>",
                "brief": "Create a new server network.",
                "description": "Creates a new network with you as the owner. Other server admins can join via `/network invite`. Networks allow servers to share ban lists, coordinate raid alerts, and maintain a shared reputation system.",
                "params": [_p("name", "text", True, "A name for the network, shown in status pages and the log server.")],
                "perm": "Administrator",
                "examples": ["/network create name:My Community Network"],
            },
            {
                "name": "/network invite",
                "usage": "/network invite [expiry_hours]",
                "brief": "Generate a one-time join code for another server.",
                "description": "Creates a single-use invite code that another server's admin can use with `/network join`. The code expires after the specified hours. Share it securely — anyone with it can add their server to your network.",
                "params": [_p("expiry_hours", "number", False, "Hours until the code expires. Default: 24.")],
                "perm": "Administrator",
                "examples": ["/network invite", "/network invite expiry_hours:48"],
            },
            {
                "name": "/network join",
                "usage": "/network join <code>",
                "brief": "Join a network using an invite code.",
                "description": "Adds this server to a network using a code from `/network invite`. Each server can only be in one network at a time.",
                "params": [_p("code", "text", True, "The invite code provided by the network owner.")],
                "perm": "Administrator",
                "examples": ["/network join code:abc123def456"],
            },
            {
                "name": "/network leave",
                "usage": "/network leave",
                "brief": "Remove this server from the network.",
                "description": "Disconnects this server from the network. Shared data (watchlist, rep) remains in the network but this server will no longer receive or contribute to synced actions.",
                "params": [],
                "perm": "Administrator",
                "examples": ["/network leave"],
            },
            {
                "name": "/network disband",
                "usage": "/network disband",
                "brief": "Dissolve the entire network (owner only).",
                "description": "Permanently deletes the network and disconnects all member servers. This cannot be undone. Only the network owner can do this.",
                "params": [],
                "perm": "Administrator",
                "examples": ["/network disband"],
            },
            {
                "name": "/network members",
                "usage": "/network members",
                "brief": "List all servers in the network.",
                "description": "Shows every server currently in this network.",
                "params": [],
                "perm": "Manage Guild",
                "examples": ["/network members"],
            },
            {
                "name": "/network status",
                "usage": "/network status",
                "brief": "Show this server's network configuration.",
                "description": "Displays which network this server belongs to, the current sync settings (bans, kicks, mutes, heuristics, raids), and whether a tamper-proof log server is configured.",
                "params": [],
                "perm": "Manage Guild",
                "examples": ["/network status"],
            },
            {
                "name": "/network sync bans",
                "usage": "/network sync bans <enabled>",
                "brief": "Sync bans across all network servers.",
                "description": "When enabled, a ban in any network server automatically triggers a ban in all other servers. The reason includes the originating server's name.",
                "params": [_p("enabled", "bool", True, "True to enable ban syncing, False to disable.")],
                "perm": "Administrator",
                "examples": ["/network sync bans enabled:True"],
            },
            {
                "name": "/network sync kicks",
                "usage": "/network sync kicks <enabled>",
                "brief": "Sync kicks across all network servers.",
                "description": "When enabled, a kick in any network server triggers a kick in all other servers.",
                "params": [_p("enabled", "bool", True, "True to enable, False to disable.")],
                "perm": "Administrator",
                "examples": ["/network sync kicks enabled:True"],
            },
            {
                "name": "/network sync mutes",
                "usage": "/network sync mutes <enabled>",
                "brief": "Sync mutes across all network servers.",
                "description": "When enabled, a mute/timeout in any network server is propagated to all other servers.",
                "params": [_p("enabled", "bool", True, "True to enable, False to disable.")],
                "perm": "Administrator",
                "examples": ["/network sync mutes enabled:True"],
            },
            {
                "name": "/network sync heuristics",
                "usage": "/network sync heuristics <enabled>",
                "brief": "Share heuristics reputation across the network.",
                "description": "When enabled, a member's suspicion score is shared across the network. If they were flagged in another server, their join score in yours is higher. Members in good standing elsewhere get a trust bonus.",
                "params": [_p("enabled", "bool", True, "True to share reputation, False to keep it local.")],
                "perm": "Administrator",
                "examples": ["/network sync heuristics enabled:True"],
            },
            {
                "name": "/network sync raids",
                "usage": "/network sync raids <enabled>",
                "brief": "Broadcast raid alerts to sibling servers.",
                "description": "When enabled, if this server detects a raid wave, all other network servers receive a raid alert and enter elevated alert mode — lowering their heuristics thresholds by 15 points for 30 minutes.",
                "params": [_p("enabled", "bool", True, "True to broadcast raid alerts, False for local-only.")],
                "perm": "Administrator",
                "examples": ["/network sync raids enabled:True"],
            },
            {
                "name": "/network watchlist add",
                "usage": "/network watchlist add <user_id> [reason]",
                "brief": "Add a user to the network watchlist.",
                "description": "Adds a user ID to the network watchlist. Every time this user joins any server in the network, all network mod channels receive an immediate alert. This is not a ban — they can still join; you're just notified instantly.",
                "params": [
                    _p("user_id", "text", True, "The Discord user ID to add to the watchlist."),
                    _p("reason", "text", False, "Why this user is being watched."),
                ],
                "perm": "Manage Guild",
                "examples": ["/network watchlist add user_id:123456789 reason:Known raider"],
            },
            {
                "name": "/network watchlist remove",
                "usage": "/network watchlist remove <user_id>",
                "brief": "Remove a user from the watchlist.",
                "description": "Removes the given user ID from the network watchlist. They will no longer trigger alerts when joining.",
                "params": [_p("user_id", "text", True, "The Discord user ID to remove.")],
                "perm": "Manage Guild",
                "examples": ["/network watchlist remove user_id:123456789"],
            },
            {
                "name": "/network watchlist list",
                "usage": "/network watchlist list",
                "brief": "List all users on the network watchlist.",
                "description": "Shows every user currently on the watchlist with their IDs and the reason they were added.",
                "params": [],
                "perm": "Manage Guild",
                "examples": ["/network watchlist list"],
            },
            {
                "name": "/network ban",
                "usage": "/network ban <user_id> [reason]",
                "brief": "Ban a user from all network servers simultaneously.",
                "description": "Issues a ban in every server in the network at once. Useful for dealing with known raiders immediately. The reason is logged with the originating server's name attached.",
                "params": [
                    _p("user_id", "text", True, "The Discord user ID to ban across the network."),
                    _p("reason", "text", False, "Reason for the ban."),
                ],
                "perm": "Ban Members",
                "examples": ["/network ban user_id:123456789 reason:Coordinated raid attack"],
            },
            {
                "name": "/network pardon",
                "usage": "/network pardon <user_id>",
                "brief": "Unban a user from all network servers.",
                "description": "Lifts the ban on a user in every server in the network and removes them from the watchlist.",
                "params": [_p("user_id", "text", True, "The Discord user ID to pardon.")],
                "perm": "Ban Members",
                "examples": ["/network pardon user_id:123456789"],
            },
            {
                "name": "/network logserver set",
                "usage": "/network logserver set <server_id>",
                "brief": "Configure a tamper-proof audit log server.",
                "description": "Designates a separate Discord server as a tamper-proof audit log for the network. The bot creates locked channels where only the bot and network owner can read. All network events (bans, kicks, honeypot triggers, raid alerts, watchlist hits) are logged there permanently.\n\nThe bot must already be in the log server before running this command.",
                "params": [_p("server_id", "text", True, "The Discord server ID to use as the log server.")],
                "perm": "Administrator",
                "examples": ["/network logserver set server_id:123456789012345678"],
            },
            {
                "name": "/network logserver unset",
                "usage": "/network logserver unset",
                "brief": "Remove the tamper-proof log server.",
                "description": "Disconnects the log server. Network events will no longer be mirrored there. The log server and its channels are not deleted.",
                "params": [],
                "perm": "Administrator",
                "examples": ["/network logserver unset"],
            },
            {
                "name": "/network logserver test",
                "usage": "/network logserver test",
                "brief": "Send a test message to the log server.",
                "description": "Posts a test message to the log server to verify the bot can reach it and the channels are set up correctly.",
                "params": [],
                "perm": "Administrator",
                "examples": ["/network logserver test"],
            },
        ],
    },
}

# ── Public endpoint-shaped view ────────────────────────────────────────────────
# Endpoint contract: a flat list of category dicts, each with
# name / description? / commands[], where each command has
# name / usage? / brief? / description? / params[]? / perm? / examples?.
# `params` entries here use "desc" (matching the in-Discord UI); the API layer
# maps that to the contract's "description" key. Extra keys (e.g. "emoji") are
# preserved for the /help UI and simply ignored by consumers that don't need them.

COMMAND_CATALOG: list[dict[str, Any]] = list(CATEGORIES.values())
